### ISSUE TITLE
Idea to bypass freeze checks by using a context manager.

### ISSUE THREAD

**Issue by ticosax** [ming-tung/django-fsm-freeze#12]
Today, django-fsm-freeze relies on `update_fields` argument of `save()` to bypass the freeze checks. But that API is internal to django and we might accidentally bypass freeze checks.

I suggest to use another approach to bypass checks, using an API that belongs to django-fsm-freeze in order to mitigate the accidental bypasses that `update_fields` brings.

Thanks to the usage of a context manager we could temporarily deactivate freeze checks

```python
>>> from django_fsm_freeze import bypass_fsm_freeze


>>> instance.save()  # fails
[...]
FreezeValidationError

>>> with bypass_fsm_freeze():
>>>    instance.save()  # succeed

```

**Comment by ming-tung** [comment]
Thanks for the idea! will look into this :)
