### ISSUE TITLE
Data freeze not working when update_fields kwargs is provided is object.save

### ISSUE THREAD

**Issue by loukou007** [ming-tung/django-fsm-freeze#2]
`object.save(update_fields=('field',))` doesn't fire Exception

**Comment by ming-tung** [comment]
That is kind of by design at the moment, to give the control to save specified fields.
https://github.com/ming-tung/django-fsm-freeze/blob/main/django_fsm_freeze/models.py#L47

**Comment by loukou007** [comment]
> That is kind of by design at the moment, to give the control to save specified fields.
> https://github.com/ming-tung/django-fsm-freeze/blob/main/django_fsm_freeze/models.py#L47

Ah got it! Sorry will close the issue then.

**Comment by ming-tung** [comment]
I will add something in the readme to clarify this - thanks for raising it.

**Comment by ming-tung** [comment]
Hey @loukou007, just FYI, I am working on a https://github.com/ming-tung/django-fsm-freeze/pull/13, which is a bit related to your question here, feel free to comment there if you have some thoughts as well.
